In [1]:
import numpy as np

In [3]:
# 0D Array/ Scalar
arr = np.array(42)
print(arr)

42


In [4]:
# 1D Array
one_dim_arr = np.array([1,2,3])
print(one_dim_arr)

[1 2 3]


In [5]:
# 2D Array
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D array
three_dim_arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(three_dim_arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
#Initialising a numpy array
num_of_rows = 3
num_of_col = 2
arrays_of_zero = np.zeros((num_of_rows, num_of_col))

print(arrays_of_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
arr_of_5s = 5 * np.full((num_of_rows, num_of_col), 7)
print(arr_of_5s)

[[35 35]
 [35 35]
 [35 35]]
