In [1]:
import numpy as np

In [3]:
# 0D Array/ Scalar
arr = np.array(42)
print(arr)

42


In [4]:
# 1D Array
one_dim_arr = np.array([1,2,3])
print(one_dim_arr)

[1 2 3]


In [5]:
# 2D Array
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3D array
three_dim_arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(three_dim_arr)
print(three_dim_arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [8]:
#Initialising a numpy array
num_of_rows = 3
num_of_col = 2
arrays_of_zero = np.zeros((num_of_rows, num_of_col))

print(arrays_of_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
arr_of_5s = 5 * np.full((num_of_rows, num_of_col), 7)
print(arr_of_5s)

[[35 35]
 [35 35]
 [35 35]]


In [13]:
start = 10
end = 25
step = 3
even_step = np.arange(start, end, step)
print(even_step)

[10 13 16 19 22]


In [15]:
identity_matrix = np.eye(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


In [29]:
random01 = np.random.random((2,3))
print(random01)

[[0.38961029 0.1184941  0.27819165]
 [0.86828731 0.07219948 0.34220207]]


In [30]:
randomintrange = np.random.randint(0,  10, (2,3))
print(randomintrange)

[[0 6 4]
 [9 7 7]]


In [41]:

a = np.array([[5,6,3], [2,5,1]])
a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [81]:
# Task 1 changing odd numbers to its negative numbers 

arr = np.array([0,2,4,5,3,7,8,9,5,1])

index = 0

for num in arr:
    if num % 2 == 1:
        arr[index] = num * -1
        index += 1
    else:
        index += 1
    
print(arr)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [56]:
arr = np.array([0,2,4,5,3,7,8,9,5,1])
arr[arr % 2 == 1] = -1 * arr[arr % 2 == 1]
print(arr)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [58]:
# Numpy array arithmetic 

a = np.array([[1,2,5], [7,1,3]])
b = np.array([[4,6,9], [2,5,1]])

In [59]:
# Adding matrices
add1 = a + b
print(add1)

[[ 5  8 14]
 [ 9  6  4]]


In [60]:
add2 = np.add(a, b)
print(add2)

[[ 5  8 14]
 [ 9  6  4]]


In [61]:
# Subtracting matrices
sub1 = a - b
print(sub1)

[[-3 -4 -4]
 [ 5 -4  2]]


In [62]:
sub2 = np.subtract(a, b)
print(sub2)

[[-3 -4 -4]
 [ 5 -4  2]]


In [63]:
# multiplying matrices

# a = np.array([[1,2,5], [7,1,3]])
# b = np.array([[4,6,9], [2,5,1]])

mul1 = a * b
print(mul1) 

[[ 4 12 45]
 [14  5  3]]


In [64]:
mul2 = np.multiply(a, b)
print(mul2)

[[ 4 12 45]
 [14  5  3]]


In [65]:
# division

div1 = a / b
print(div1)

div2 = np.divide(a, b)
print(div2)

[[0.25       0.33333333 0.55555556]
 [3.5        0.2        3.        ]]


In [66]:
# a = np.array([[1,2,5], [7,1,3]])
# b = np.array([[4,6,9], [2,5,1]])

maxi = a.max()
print(maxi)

7


In [67]:
# standard deviation
std_dev = np.std(a)
print(std_dev)

2.1921577396609844


In [87]:
# Task 2 computing length of triangle

from numpy import linalg as la
import math

a = np.array([0,0])
b = np.array([0,3])
c = np.array([1.5,0])

ab2 = la.norm(a - b)
ac2 = la.norm(a - c)
bc2 = la.norm(b - c)

print(math.sqrt(ab2))
print(math.sqrt(ac2))
print(math.sqrt(bc2))

1.7320508075688772
1.224744871391589
1.8314207507423532


In [91]:
new_var = np.array([[1,2,3], [4,5,6]])
print(new_var)

[[1 2 3]
 [4 5 6]]


In [92]:
new_var_t = np.transpose(new_var)
print(new_var_t)

[[1 4]
 [2 5]
 [3 6]]


In [93]:
reshape1 = np.reshape(new_var, (3,2))
print(reshape1)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
# stacking numpy array
# horizontal stacking
# vertical stacking

matrix1 = np.array([[11, 12, 13], [14, 15, 16]])
matrix2 = np.array([[17, 18, 19], [20, 21, 22]])

stack_horiz = np.hstack([matrix1, matrix2])
print(stack_horiz)

[[11 12 13 17 18 19]
 [14 15 16 20 21 22]]


In [100]:
stack_vert = np.vstack([matrix1, matrix2])
print(stack_vert)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [105]:
# concatination of array
# axis0 = row, axis1 = column
refined_column = np.concatenate((matrix1, matrix2), axis = 1)
print(refined_column)

[[11 12 13 17 18 19]
 [14 15 16 20 21 22]]


In [102]:
refined_row = np.concatenate((matrix1, matrix2), axis = 0)
print(refined_row)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [106]:
# saving a file
np.save("array_a", refined_row)
# saving multiple 
np.savez("refined_save", arr1 = refined_row, arr2 = refined_column)


In [107]:
load_refined = np.load("array_a.npy")

In [109]:
# saving contents of the saved npz file
content = np.load("refined_save.npz")
anpz = content["arr1"]
bnpz = content["arr2"]
print(bnpz)

[[11 12 13 17 18 19]
 [14 15 16 20 21 22]]


In [ ]:
# import a csv file

acsv = np.loadtxt("")

In [113]:
num = np.array([1.0, 2.5, 3.4])
print(num)

rounded = np.round(num)
print(rounded)

[1.  2.5 3.4]
[1. 2. 3.]
